# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../QTProjects/designs/parse_tool.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 400))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.db_tab = QtWidgets.QWidget()
        self.db_tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.db_tab.setObjectName("db_tab")
        self.tabWidget.addTab(self.db_tab, "")
        self.wf_tab = QtWidgets.QWidget()
        self.wf_tab.setAutoFillBackground(False)
        self.wf_tab.setObjectName("wf_tab")
        self.export_button = QtWidgets.QPushButton(self.wf_tab)
        self.export_button.setGeometry(QtCore.QRect(250, 310, 241, 31))
        self.export_button.setDefault(False)
        self.export_button.setFlat(False)
        self.export_button.setObjectName("export_button")
        self.workflow_list = QtWidgets.QListView(self.wf_tab)
        self.workflow_list.setGeometry(QtCore.QRect(10, 50, 221, 291))
        self.workflow_list.setObjectName("workflow_list")
        self.search_box = QtWidgets.QLineEdit(self.wf_tab)
        self.search_box.setGeometry(QtCore.QRect(10, 10, 221, 28))
        self.search_box.setAutoFillBackground(True)
        self.search_box.setObjectName("search_box")
        self.effected_list = QtWidgets.QListView(self.wf_tab)
        self.effected_list.setGeometry(QtCore.QRect(250, 181, 241, 121))
        self.effected_list.setObjectName("effected_list")
        self.effected_label = QtWidgets.QLabel(self.wf_tab)
        self.effected_label.setGeometry(QtCore.QRect(250, 160, 241, 21))
        self.effected_label.setAutoFillBackground(False)
        self.effected_label.setStyleSheet("background-color: white;")
        self.effected_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.effected_label.setObjectName("effected_label")
        self.source_list = QtWidgets.QListView(self.wf_tab)
        self.source_list.setGeometry(QtCore.QRect(250, 31, 241, 121))
        self.source_list.setObjectName("source_list")
        self.source_label = QtWidgets.QLabel(self.wf_tab)
        self.source_label.setGeometry(QtCore.QRect(250, 10, 241, 21))
        self.source_label.setAutoFillBackground(False)
        self.source_label.setStyleSheet("background-color: white;")
        self.source_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.source_label.setObjectName("source_label")
        self.tabWidget.addTab(self.wf_tab, "")
        self.tw_tab = QtWidgets.QWidget()
        self.tw_tab.setObjectName("tw_tab")
        self.tabWidget.addTab(self.tw_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parsing tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.db_tab), _translate("MainWindow", "Databases"))
        self.export_button.setText(_translate("MainWindow", "Export results to CSV"))
        self.search_box.setPlaceholderText(_translate("MainWindow", "Search workflow... "))
        self.effected_label.setText(_translate("MainWindow", "Effected tables (insert/update)"))
        self.source_label.setText(_translate("MainWindow", "Source tables"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wf_tab), _translate("MainWindow", "Workflows"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tw_tab), _translate("MainWindow", "Tableua Workbooks"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))

